const { Console } = require("console")
const path= require("path")
console.log(path.resolve('./app.js'))
console.log(path.relative('./',"./temp/utilis.js"))
console.log(path.extname('./app.js'))
console.log(path.dirname('./temp/utilis.js'))
console.log(path.join(_dirname, 'app.js'))
